# TFG Application Properties
app.root=env.applRoot
app.environment=env.environment
spring.datasource.username=coredb.userName
spring.datasource.databaseName=coredb.dbName
spring.datasource.portNumber=coredb.dbPort
spring.datasource.hostname=hosts.db2Host
